### ISSUE TITLE
P1 - ver82jakub2 - 888739d6-2c64-4f45-b719-25555fbbab52

### ISSUE THREAD

**Issue by tajgr** [robotika/subt-artf#37]
Dvakrát drona, dvakrát Freyja
Sice jsme získali 4 body, ale Freyja C podle všeho vůbec nevyjela, a Freyja D po chvilce vyjela ven a na startovací oblasti vyložila dva drobečky.

**Comment by tajgr** [comment]
![state tlog](https://user-images.githubusercontent.com/6401714/95733297-39352c80-0c82-11eb-9534-fe39a4072900.png)

**Comment by tajgr** [comment]
Log pro C má jen 11kB (asi jen konfigurace).

python -m osgar.replay --module app logs/virtual/82jakub2cp1r1/aws-ver82jakub2cp1r1-C600L.log 
original args: b"['/osgar-ws/src/osgar/subt/__main__.py', 'run', '/osgar-ws/src/osgar/subt/zmq-subt-x2.json', '/osgar-ws/src/osgar/subt/subt-freyja.json', '--log', '/osgar-ws/logs/subt-freyja-2020-10-12T01.14.15.log', '--side', 'auto', '--walldist', '1.0', '--speed', '1.5', '--note', 'run_solution.bash']"
__main__     WARNING  Missing name: rosmsg.origin
__main__     WARNING  Missing name: rosmsg.image
__main__     WARNING  Missing name: rosmsg.sim_time_sec
__main__     WARNING  Missing name: detector.artf
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jakub/miniconda3/envs/osgar/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/jakub/miniconda3/envs/osgar/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jakub/git/osgar/subt/main.py", line 961, in play
    return self.play_virtual_track()
  File "/home/jakub/git/osgar/subt/main.py", line 918, in play_virtual_track
    self.stdout("SubT Challenge Ver82!")
  File "/home/jakub/git/osgar/subt/main.py", line 677, in stdout
    self.bus.publish('stdout', contents)
  File "/home/jakub/git/osgar/osgar/bus.py", line 184, in publish
    dt, stream_id, bytes_data = next(self.reader)
  File "/home/jakub/git/osgar/osgar/logger.py", line 233, in __next__
    return next(self.gen)
StopIteration

maximum delay: 0:00:00

**Comment by zwn** [comment]
Drony měli lokalizaci v pořádku až do okamžiku, kdy došly baterky:
<pre>
Processing logfile: aws-ver82jakub2cp1r1-A1300L.log
  Autodetected name: A1300L
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 1316
  Ground truth seconds: 1410
  sim_time_sec:   454, error:  1.09m, distance:  266.93m from origin, path:  434.58m
  sim_time_sec:   548, error:  2.03m, distance:  206.66m from origin, path:  537.87m
  sim_time_sec:   565, error:  3.02m, distance:  190.82m from origin, path:  556.38m
  sim_time_sec:   607, error:  4.04m, distance:  163.49m from origin, path:  596.00m
  sim_time_sec:  1281, error:  6.41m, distance:  257.54m from origin, path: 1292.11m
  Maximum error: 356.76m -> FAIL
Processing logfile: aws-ver82jakub2cp1r1-B10W1300R.log
  Autodetected name: B10W1300R
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 1322
  Ground truth seconds: 1410
  sim_time_sec:   225, error:  1.04m, distance:  154.97m from origin, path:  188.08m
  sim_time_sec:   706, error:  2.01m, distance:  304.95m from origin, path:  670.69m
  sim_time_sec:   799, error:  3.00m, distance:  353.84m from origin, path:  748.34m
  sim_time_sec:  1048, error:  4.00m, distance:  170.93m from origin, path: 1012.31m
  sim_time_sec:  1144, error:  5.05m, distance:  104.39m from origin, path: 1113.25m
  Maximum error: 388.03m -> FAIL
</pre>

**Comment by zwn** [comment]
Freyja D byla ok až do cca 300s:

<pre>Processing logfile: aws-ver82jakub2cp1r1-D100W600R.log
  Autodetected name: D100W600R
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 330
  Ground truth seconds: 1410
  sim_time_sec:   294, error:  1.17m, distance:   29.10m from origin, path:  139.90m
  sim_time_sec:   295, error:  2.88m, distance:   27.85m from origin, path:  141.99m
  sim_time_sec:   296, error:  4.37m, distance:   27.70m from origin, path:  142.57m
  sim_time_sec:   299, error:  6.22m, distance:   27.87m from origin, path:  143.05m
  Maximum error: 283.16m -&gt; FAIL
</pre>

Za pozornost ale IMO stojí chyba v ose Z:

![image](https://user-images.githubusercontent.com/1130051/95742310-1578e300-0c90-11eb-92b0-9c3a408e916b.png)

Takhle nějak jsem ti představoval :grin:

**Comment by zwn** [comment]
Log Freyji C obsahuje pouze 27 položek, ale k samotnému nastartování jich je třeba víc jak 50. Tj. z nějakého důvodu se to vůbec nepodařilo pustit. Z nějakého důvodu to na začátku "zaspalo" a pak to asi zabil ten timeout, co jsem říkal, že s ním něco udělám:

![image](https://user-images.githubusercontent.com/1130051/95743123-8371da00-0c91-11eb-85dc-383bf1180904.png)

versus

![image](https://user-images.githubusercontent.com/1130051/95743177-9ab0c780-0c91-11eb-9d35-b57acf6a5217.png)

Všimněte si, jak je tam v tom prvním cca o 1s později.

**Comment by tajgr** [comment]
Já ještě k artefaktům:
- drona A našla jen lano, v --stream reporter.artf_all, vidím poslední řádek:
3:48:51.745617 11 [['TYPE_ROPE', 212283, -4866, 1365], ['TYPE_ROPE', 213254, -4857, 1490], ['TYPE_ROPE', 215589, -10346, 1148]], tj. pokus o reportování 3x
správná pozice by měla být [288.85, 0.91, 145.94]
- drona B, --stream reporter.artf_all:
3:50:34.973956 26 [['TYPE_ROPE', 212283, -4866, 1365], ['TYPE_ROPE', 213254, -4857, 1490], ['TYPE_BACKPACK', 231332, -163823, 2215], ['TYPE_PHONE', 227593, -267364, 24641], ['TYPE_ROPE', 90057, -201130, 2388], ['TYPE_PHONE', 78143, -49287, 22347]], tj. pět různých artefaktů. 

Chtělo by to ještě prověřit který artefakt se nepodařilo správně reportovat a kudy se to vlastně protlačilo ven.

Falešné detekce 3, všechny ve startovní oblasti a všechny patrně zablokovány.

**Comment by tajgr** [comment]
Tak pro ten druhý telefon nesedí pozice o 0.26 m,
reportováno `['TYPE_PHONE', 78143, -49287, 22347]`
správně: `[74.37, -45.63, 22.06]`

**Comment by zwn** [comment]
Je problém pozice robota nebo pozice telefonu vůči robotovi?

**Comment by zwn** [comment]
Co kdo našel je dobře vidět zde:

<pre>$ ogger aws-ver82jakub2cp1r1-A1300L.log --stream app.artf_xyz
0:44:49.999610 23 [[&apos;TYPE_ROPE&apos;, 212283, -4866, 1365]]
3:18:43.065529 23 [[&apos;TYPE_ROPE&apos;, 215589, -10346, 1148]]
</pre>

<pre>$ ogger aws-ver82jakub2cp1r1-B10W1300R.log --stream app.artf_xyz
1:17:08.791317 19 [[&apos;TYPE_ROPE&apos;, 213254, -4857, 1490]]
1:49:16.528663 19 [[&apos;TYPE_BACKPACK&apos;, 231332, -163823, 2215]]
2:14:18.166823 19 [[&apos;TYPE_PHONE&apos;, 227593, -267364, 24641]]
2:50:25.945609 19 [[&apos;TYPE_ROPE&apos;, 90057, -201130, 2388]]
3:16:55.099387 19 [[&apos;TYPE_PHONE&apos;, 78143, -49287, 22347]]
</pre>

**Comment by zwn** [comment]
Dále co kdo reportoval a s jakým výsledkem je dobře vidět zde:

<pre>$ ogger aws-ver82jakub2cp1r1-A1300L.log --stream rosmsg.base_station
1:54:13.939171 42 {&apos;report_id&apos;: 3, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
1:54:13.939980 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
...
</pre>

Drona A má dva reporty (id 3 a 4) - obě jsou to asi lana. A u obou to vypadá, že je zdrojem právě drona A. Není to divné, když je drona A nemá v `app.artf_xyz`?

**Comment by zwn** [comment]
Také ještě nevím, co jsi mám myslet o tomto:

<pre>$ ogger aws-ver82jakub2cp1r1-B10W1300R.log --stream rosmsg.base_station
3:41:55.778965 42 {&apos;report_id&apos;: 5, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:41:55.779840 42 {&apos;report_id&apos;: 5, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
3:41:55.780934 42 {&apos;report_id&apos;: 5, &apos;artifact_type&apos;: 0, &apos;artifact_position&apos;: [231.33, -163.82, 2.21], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:41:55.782024 42 {&apos;report_id&apos;: 6, &apos;artifact_type&apos;: 5, &apos;artifact_position&apos;: [227.59, -267.36, 24.64], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:41:55.783070 42 {&apos;report_id&apos;: 7, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [90.06, -201.13, 2.39], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:41:55.784157 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 5, &apos;artifact_position&apos;: [78.14, -49.29, 22.35], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
3:41:55.785251 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:41:56.040190 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
3:41:56.041537 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 0, &apos;artifact_position&apos;: [231.33, -163.82, 2.21], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:41:56.042599 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 5, &apos;artifact_position&apos;: [227.59, -267.36, 24.64], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:41:56.043643 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [90.06, -201.13, 2.39], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:41:56.044706 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 5, &apos;artifact_position&apos;: [78.14, -49.29, 22.35], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
3:43:39.767255 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:43:39.768358 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
3:43:39.769547 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 0, &apos;artifact_position&apos;: [231.33, -163.82, 2.21], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:43:39.770980 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 5, &apos;artifact_position&apos;: [227.59, -267.36, 24.64], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:43:39.771937 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [90.06, -201.13, 2.39], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:43:39.773063 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 5, &apos;artifact_position&apos;: [78.14, -49.29, 22.35], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
3:43:39.774516 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
3:43:39.775536 42 {&apos;report_id&apos;: 8, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
...
</pre>

`report_id` by mělo být pořadové číslo našeho reportu. Ale podle těchto dat to vypadá, že je to totálně zmatené. Například `report_id` 5 je přiřazeno zjevně několika různým reportům. Stejně tak `report_id` 8. Stejný problém je vidět zde:

<pre>$ ogger aws-ver82jakub2cp1r1-A1300L.log --stream rosmsg.base_station
1:54:13.939171 42 {&apos;report_id&apos;: 3, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
1:54:13.939980 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
1:54:13.940911 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
1:55:58.374730 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
1:55:58.376020 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
1:55:58.420814 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
1:55:58.421825 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
1:57:42.413206 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
...
</pre>

ale tentokrát s `report_id` 4.

**Comment by zwn** [comment]
No, ale díky za ty falešné reporty. Když dám dohromady přes `sim_time_sec` tohle:

<pre>0:48:13.864175 33 300
0:48:17.682494 43 {&apos;report_id&apos;: 1, &apos;artifact_type&apos;: 7, &apos;artifact_position&apos;: [-24.42, -18.19, 0.01], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
</pre>

```yml
- event:
  id: 23
  type: artifact_report_attempt
  time_sec: 300
  reported_pose: -14.42 -18.19 0.01
  reported_artifact_type: TYPE_RESCUE_RANDY
  closest_artifact_name: rescue_randy_3
  distance: 220.569
  points_scored: 0
  total_score: 0
```

Tak vidím, že se jedná o neplatný report, ale přitom v odpovědi je <tt>&apos;report_status&apos;: &apos;scored&apos;</tt> :worried:

**Comment by zwn** [comment]
Tj. asi jediné, čeho se můžeme chytat, při snaze o deduplikaci reportů je `score_change`.

**Comment by zwn** [comment]
Alespoň se mi podařilo snad potvrdit, že když poslu správný artefakt dvakrát za sebou se dvěma různými pozicemi, tak se oba pokusy započítají do celkového bodování, ale o tom druhém pokusu už nemám informaci o tom, zda by býval byl započítaný či nikoli. Tj. z pohledu robota to druhé odeslání stejného lana o kousek vedle vypadá, jako špatný report.

```yml
- event:
  id: 50
  type: artifact_report_attempt
  time_sec: 680
  reported_pose: 222.28 -4.87 1.36
  reported_artifact_type: TYPE_ROPE
  closest_artifact_name: rope_2
  distance: 0.593391
  points_scored: 1
  total_score: 1
- event:
  id: 51
  type: artifact_report_attempt
  time_sec: 680
  reported_pose: 223.25 -4.86 1.49
  reported_artifact_type: TYPE_ROPE
  closest_artifact_name: rope_2
  distance: 1.50608
  points_scored: 0
  total_score: 1
- event:
  id: 52
  type: duplicate_artifact_report
  time_sec: 680
  reported_pose: 222.28 -4.87 1.36
  reported_artifact_type: TYPE_ROPE
- event:
  id: 53
  type: duplicate_artifact_report
  time_sec: 680
  reported_pose: 223.25 -4.86 1.49
  reported_artifact_type: TYPE_ROPE
```

<pre>1:54:13.543550 32 680
1:54:13.939171 42 {&apos;report_id&apos;: 3, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [212.28, -4.87, 1.36], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 1}
1:54:13.939980 42 {&apos;report_id&apos;: 4, &apos;artifact_type&apos;: 13, &apos;artifact_position&apos;: [213.25, -4.86, 1.49], &apos;report_status&apos;: &apos;scored&apos;, &apos;score_change&apos;: 0}
</pre>
